[package]
name = "good_lp"
version = "0.0.4"
authors = ["Ophir LOJKINE <contact@ophir.dev>"]
edition = "2018"
repository = "https://github.com/lovasoa/good_lp"
documentation = "https://docs.rs/good_lp"
description = " Linear Programming for Rust, with an user-friendly API. This crate allows modeling LP problems, and let's you solve them with various solvers."
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default = ["coin_cbc"]

[dependencies]
coin_cbc = { version = "0.1", optional = true }
minilp = { version = "0.2", optional = true }

[dev-dependencies]
trybuild = "1"