name: Rust

on:
  push:
    branches: [ main ]
    paths: ["**.rs", "Cargo.toml", ".github/workflows/rust.yml", "tests/**.stderr"]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt-get install coinor-cbc coinor-libcbc-dev
          rustup component add rustfmt
      - name: Build
        run: cargo build --all-features --tests
      - name: Run tests
        run: cargo test --all-features
      - name: Run tests with minilp
        run: cargo test --no-default-features --features minilp
      - name: Check formatting
        run: cargo fmt -- --check
      - run: cargo bench
