name: Rust

on:
  push:
    branches: [ main ]
    paths: ["**.rs", "Cargo.toml", ".github/workflows/rust.yml"]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install coinor-cbc coinor-libcbc-dev
    - name: Build
      run: cargo build --verbose --all-features --tests
    - name: Run tests
      run: cargo test --verbose --all-features
